[package]
name = "bc-r"
version = "0.0.1"
authors = ["akgvn <akgvn@**.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
